version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    environment:
      OSRM_BASE_URL: http://osrm:5000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - osrm

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demouser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    command: >
      sh -c "
      if [ ! -f /data/$${OSRM_GRAPH_BASENAME}.osrm ]; then
        osrm-extract -p /opt/$${OSRM_LUA_PROFILE}.lua /data/$${OSRM_EXTRACT_FILE} &&
        osrm-partition /data/$${OSRM_GRAPH_BASENAME}.osrm &&
        osrm-customize /data/$${OSRM_GRAPH_BASENAME}.osrm;
      fi &&
      osrm-routed --algorithm mld /data/$${OSRM_GRAPH_BASENAME}.osrm"
    environment:
      OSRM_EXTRACT_FILE: ${OSRM_EXTRACT_FILE:-region.osm.pbf}
      OSRM_GRAPH_BASENAME: ${OSRM_GRAPH_BASENAME:-region}
      OSRM_LUA_PROFILE: ${OSRM_LUA_PROFILE:-car}
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data

volumes:
  postgres_data:

